// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.demo.shell.protocol;

public final class UserOuterClass {
  private UserOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\010protocol\"C\n\004User\022\016\n\006userId" +
      "\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\022\013\n\003age\030\003 \001(\021\022\014\n" +
      "\004name\030\004 \001(\t2\233\001\n\013UserService\022+\n\007getUser\022\016" +
      ".protocol.User\032\016.protocol.User\"\000\022.\n\010getU" +
      "sers\022\016.protocol.User\032\016.protocol.User\"\0000\001" +
      "\022/\n\tsaveUsers\022\016.protocol.User\032\016.protocol" +
      ".User\"\000(\001B%\n\027com.demo.shell.protocolP\001Z\010" +
      "protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_User_descriptor,
        new java.lang.String[] { "UserId", "Username", "Age", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
